-- Clean existing data
TRUNCATE TABLE "policies" RESTART IDENTITY CASCADE;

-- Insert Terms Policies
INSERT INTO "policies" (policy_id, policy_type, version_number, language_code, effective_date, content_html, content_plain, checkbox_text, created_at)
  VALUES (gen_random_uuid (), 'terms', 1, 'en', '2025-06-01 00:00:00', '<h1>Terms and Conditions</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. These Terms govern your use of our platform. By using our services, you agree to these terms. Please read these terms carefully before accessing or using our services.</p>', 'Terms and Conditions\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. These Terms govern your use of our platform. By using our services, you agree to these terms. Please read these terms carefully before accessing or using our services.', 'I accept the Terms and Conditions', CURRENT_TIMESTAMP),
  (gen_random_uuid (), 'terms', 1, 'pl', '2025-06-01 00:00:00', '<h1>Regulamin</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Niniejszy Regulamin określa zasady korzystania z naszej platformy. Korzystając z naszych usług, akceptujesz te warunki. Prosimy o uważne zapoznanie się z tymi warunkami przed uzyskaniem dostępu lub korzystaniem z naszych usług.</p>', 'Regulamin\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Niniejszy Regulamin określa zasady korzystania z naszej platformy. Korzystając z naszych usług, akceptujesz te warunki. Prosimy o uważne zapoznanie się z tymi warunkami przed uzyskaniem dostępu lub korzystaniem z naszych usług.', 'Akceptuję Regulamin', CURRENT_TIMESTAMP);

-- Insert Privacy Policies
INSERT INTO "policies" (policy_id, policy_type, version_number, language_code, effective_date, content_html, content_plain, checkbox_text, created_at)
  VALUES (gen_random_uuid (), 'privacy', 1, 'en', '2025-06-01 00:00:00', '<h1>Privacy Policy</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. This is our Data Policy. We collect and process your data in accordance with applicable laws. We are committed to protecting your personal information and ensuring its confidentiality.</p>', 'Privacy Policy\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. This is our Data Policy. We collect and process your data in accordance with applicable laws. We are committed to protecting your personal information and ensuring its confidentiality.', 'I accept the Data Policy', CURRENT_TIMESTAMP),
  (gen_random_uuid (), 'privacy', 1, 'pl', '2025-06-01 00:00:00', '<h1>Polityka Prywatności</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. To jest nasza Polityka Danych. Zbieramy i przetwarzamy Państwa dane zgodnie z obowiązującymi przepisami. Zobowiązujemy się do ochrony Państwa danych osobowych i zapewnienia ich poufności.</p>', 'Polityka Prywatności\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. To jest nasza Polityka Danych. Zbieramy i przetwarzamy Państwa dane zgodnie z obowiązującymi przepisami. Zobowiązujemy się do ochrony Państwa danych osobowych i zapewnienia ich poufności.', 'Akceptuję Politykę Danych', CURRENT_TIMESTAMP);

